CUDA_VISIBLE_DEVICES=0 python demo.py \
  --height 32 \
  --width 100 \
  --voc_type ALLCASES_SYMBOLS \
  --arch ResNet_ASTER \
  --with_lstm \
  --max_len 20 \
  --STN_ON \
  --beam_width 5 \
  --tps_inputsize 32 64 \
  --tps_outputsize 32 100 \
  --tps_margins 0.05 0.05 \
  --stn_activation none \
  --num_control_points 20 \
  --resume ./data/logs0/baseline/model_best.pth.tar \
  --image_path ./01_05_2_par.jpg